name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.1
          dune-cache: true

      - name: Install dependencies
        run: |
          opam update
          opam install -y dune alcotest qcheck qcheck-alcotest zarith

          # если у тебя есть opam-файлы и хочешь, чтобы тянуло зависимости из них:
          # opam install . --deps-only --with-test -y || echo "no opam package, skipping"

      - name: Build
        run: |
          dune build

      - name: Test
        run: |
          dune test

      - name: Format check
        run: |
          dune build @fmt || (echo "Run: dune fmt" && exit 1)
